/**
 * Initial dataset for Demo Mode — static values for modeling / exploration only.
 */

import type { AppData, Holding, Scenario } from "./storage";

const T0 = "2024-06-01T12:00:00.000Z";

const HOLDINGS: Holding[] = [
  {
    id: "demo-vti",
    ticker: "VTI",
    exchange: "US",
    shares: 40,
    avg_cost: 248.2,
    initial_avg_cost: 252,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
  {
    id: "demo-aapl",
    ticker: "AAPL",
    exchange: "US",
    shares: 55,
    avg_cost: 198.5,
    initial_avg_cost: 210,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
  {
    id: "demo-msft",
    ticker: "MSFT",
    exchange: "US",
    shares: 22,
    avg_cost: 382.4,
    initial_avg_cost: 395,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
  {
    id: "demo-nvda",
    ticker: "NVDA",
    exchange: "US",
    shares: 28,
    avg_cost: 142.8,
    initial_avg_cost: 168,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
  {
    id: "demo-shop",
    ticker: "SHOP",
    exchange: "TSX",
    shares: 18,
    avg_cost: 118.4,
    initial_avg_cost: 132.5,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
  {
    id: "demo-jpm",
    ticker: "JPM",
    exchange: "US",
    shares: 35,
    avg_cost: 198.75,
    initial_avg_cost: 205,
    fee: 0,
    fee_type: "flat",
    fee_value: 0,
    created_at: T0,
  },
];

const SCENARIOS: Scenario[] = [
  {
    id: "demo-sc-1",
    holding_id: "demo-nvda",
    ticker: "NVDA",
    method: "price_target",
    input1_label: "Buy price",
    input1_value: 112.5,
    input2_label: "Target average cost",
    input2_value: 125,
    include_fees: false,
    fee_amount: 0,
    buy_price: 112.5,
    shares_to_buy: 43,
    budget_invested: 4837.5,
    fee_applied: 0,
    total_spend: 4837.5,
    new_total_shares: 71,
    new_avg_cost: 125,
    recommended_target: null,
    budget_percent_used: null,
    notes: null,
    created_at: T0,
  },
  {
    id: "demo-sc-2",
    holding_id: "demo-shop",
    ticker: "SHOP",
    method: "price_budget",
    input1_label: "Buy price",
    input1_value: 105,
    input2_label: "Max budget",
    input2_value: 1200,
    include_fees: false,
    fee_amount: 0,
    buy_price: 105,
    shares_to_buy: 11.43,
    budget_invested: 1200,
    fee_applied: 0,
    total_spend: 1200,
    new_total_shares: 29.43,
    new_avg_cost: 116.2,
    recommended_target: 116.2,
    budget_percent_used: 100,
    notes: null,
    created_at: T0,
  },
  {
    id: "demo-sc-3",
    holding_id: "demo-aapl",
    ticker: "AAPL",
    method: "price_target",
    input1_label: "Buy price",
    input1_value: 172,
    input2_label: "Target average cost",
    input2_value: 185,
    include_fees: false,
    fee_amount: 0,
    buy_price: 172,
    shares_to_buy: 52,
    budget_invested: 8944,
    fee_applied: 0,
    total_spend: 8944,
    new_total_shares: 107,
    new_avg_cost: 185,
    recommended_target: null,
    budget_percent_used: null,
    notes: null,
    created_at: T0,
  },
  {
    id: "demo-sc-4",
    holding_id: "demo-vti",
    ticker: "VTI",
    method: "price_budget",
    input1_label: "Buy price",
    input1_value: 235,
    input2_label: "Max budget",
    input2_value: 2500,
    include_fees: false,
    fee_amount: 0,
    buy_price: 235,
    shares_to_buy: 10.64,
    budget_invested: 2500,
    fee_applied: 0,
    total_spend: 2500,
    new_total_shares: 50.64,
    new_avg_cost: 244.5,
    recommended_target: 244.5,
    budget_percent_used: 100,
    notes: null,
    created_at: T0,
  },
];

/** Deep-cloned initial AppData for demo sandbox. */
export function createInitialDemoAppData(): AppData {
  return {
    version: 1,
    holdings: HOLDINGS.map((h) => ({ ...h })),
    scenarios: SCENARIOS.map((s) => ({ ...s })),
    transactions: [],
    whatIfComparisons: [],
    optimizationScenarios: [],
  };
}
